# -*- coding: utf-8 -*-
"""Cópia de Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WhVxn8NKC6UZ8TcFDZLf1Qkl8Tio97CB
"""

#Faça um programa que leia 5 números e informe o maior número.

maior_numero = 0
for contador in range(5):
  numero = int(input("digite o numero"))
  if numero > maior_numero:
    maior_numero = numero

    print(maior_numero)

#Faça um programa que verifique e mostre os números entre 1.000 e 2.000
#(inclusive) que, quando divididos por 11 produzam resto igual a 2.

for contador in range(1000, 2001):
  if contador % 11 == 2:
    print(contador)

#Faça um programa que leia 5 números e informe a soma e a média dos numeros.

soma = 0
for i in range(5):
  numero = float(input(f"digite o {i+1}º numero: "))
  soma += numero
  media = soma/5

  print(f"a soma dos numeros e: {soma} e a media {media}")

#Faça um programa que receba um número e usando laços de repetição calcule e mostre a tabuada desse número.

numero = int(input("digite um numero para calcular a tabuada"))
print(f"tabuada do {numero}")
for i in range(1, 11):
 resultado = 1 * i
 print(resultado)

#Faça um programa que mostre as tabuadas dos números de 1 a 10 usando laços de repetição.

for i in range(1, 11):
  print(f"taboada do {i}")
  for a in range(1, 11):
   resultado = i * a
   print(f"{i} + {a} = {resultado}")

#Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.

for i in range(1, 21):
 print(i)
for i in range(1, 21):
 print(i, end = '')

#Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50.

for i in range(1, 51):
  if i % 2 != 0:
    print(i)

#Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.

numero1 = int(input("digite o primeiro numero inteiro"))
numero2 = int(input("digite o segundo numero inteiro"))
for i in range(numero1, numero2):
 print(i)

#Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi superior a loja B (faturamento = 54000). Se o faturamento atingir esse valor
#mostre na tela uma mensagem contendo em quanto foi superado ofaturamento.


lojab = 54000
lojaa = 0
for i in range(5):
  V = float(input("digite o valor"))
lojaa += V
if lojaa > lojab:
   print("o faturamento da loja a é maior que loja b")
elif lojab > lojab:
   print("o faturamento da loja b é maior que a loja a")
else:
   print("o valor do faturamento de ambas é igual ")